### ISSUE TITLE
getting unrecognised issue

### ISSUE THREAD

**Issue by nayanleo** [iArunava/ENet-Real-Time-Semantic-Segmentation#7]
python init.py --mode test -m /datasets/CamVid/ckpt-enet.pth  -i img.jpg 

Traceback (most recent call last):
  File "init.py", line 153, in <module>
    test(FLAGS)
  File "/home/vikram/OBJECT DETECTION & TRACKING/ENet-Real-Time-Semantic-Segmentation/test.py", line 12, in test
    if not FLAGS.model_path.endswith('.pth'):
AttributeError: 'Namespace' object has no attribute 'model_path'

**Comment by iArunava** [comment]
I updated. Please
`git pull` and try again

**Comment by AvivSham** [comment]
More than a week without reply
