### ISSUE TITLE
undefined variable

### ISSUE THREAD

**Issue by csxeba** [iArunava/ENet-Real-Time-Semantic-Segmentation#8]
`python init.py --mode test -i img.jpg -m datasets/CamVid/ckpt-enet.pth`

Throws

```
Traceback (most recent call last):
  File "init.py", line 153, in <module>
    test(FLAGS)
  File ".../ENet-Real-Time-Semantic-Segmentation/test.py", line 32, in test
    out1 = enet(tmg.float()).squeeze(0)
  File ".../.conda/envs/dl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/Prog/PycharmProjects/ENet-Real-Time-Semantic-Segmentation/models/ENet.py", line 194, in forward
    x, i1 = self.b10(x)
  File ".../.conda/envs/dl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File ".../ENet-Real-Time-Semantic-Segmentation/models/RDDNeck.py", line 108, in forward
    extras = extras.to(device)
NameError: name 'device' is not defined
```

**Comment by AvivSham** [comment]
I made some changes try to run it now

**Comment by csxeba** [comment]
Thanks, it works now!

**Comment by AvivSham** [comment]
you are welcome :)
